### ISSUE TITLE
3D Tetris is extremely unstable, crashes on intro

### ISSUE THREAD

**Issue by rari-teh** [skyfloogle/red-viper#30] opened 2024-03-02 01:45 UTC
Loading 3D Tetris as your first ROM leads it to an arm11 crash during the intro, before the title screen [(dump)](https://github.com/skyfloogle/red-viper/files/14467632/crash_dump_00000009.dmp). Loading it after some other game is loaded gives it varying degrees of stability, from working seemingly just fine to crashing after a couple minutes of gameplay seemingly at random, with an error popup (changing ROMs to 3D Tetris while in Virtual Boy Wario Land’s post stage completion treasure screen seems to make for a decently stable run, fwiw).

**Comment by skyfloogle** [comment] 2024-03-02 02:32
Duplicate of #6

**Closed** 2024-03-02 02:33 UTC
