### ISSUE TITLE
3-D Tetris Freeze

### ISSUE THREAD

**Issue by atmosbreak** [skyfloogle/red-viper#6] opened 2024-02-26 23:31 UTC
3-D Tetris froze not very far into 3-D Tetris Type A mode. Playing on an original 3DS XL.

**Comment by LilROC109** [comment] 2024-02-27 00:33
Also had this issue, noticed that some of the graphics turn to black on the title screen and will not let me press start, a reset is required

**Comment by placeboyue** [comment] 2024-02-27 03:27
my o3ds also froze

**Comment by eliaskma** [comment] 2024-02-27 03:33
yes, my new3DS also froze on 3-D Tetris

**Comment by vaguerant** [comment] 2024-02-27 09:59
It seems plausible that this is a duplicate of #1. Red Alarm and 3-D Tetris were both developed by T&E Soft; if the same issue occurs in Golf, a third game from the same dev, that would suggest even more strongly that there's something T&E was doing in their code that Red Viper doesn't like.

**Closed** 2024-02-29 22:52 UTC

**Comment by skyfloogle** [comment] 2024-02-29 22:54
I set up effectively a TAS to consistently reproduce a crash during the intro, and confirmed that the linked commit fixes it. Similar conditions occur in Red Alarm, so it's likely that @vaguerant was correct.

**Comment by vaguerant** [comment] 2024-03-01 06:23
Dropping a note in here that Golf does seem to suffer from the same issue. I haven't experienced it myself, but watched a video on YouTube of somebody demoing Red Viper, and they had a very similar looking crash happen at 6:44. Link to timestamp:

[![VIRTUAL BOY ON 3DS?!?! - Testing A New Virtual Boy Emulator For The 3DS](https://img.youtube.com/vi/iewS-AHteq0/maxresdefault.jpg)](https://youtu.be/iewS-AHteq0?si=jioj5dFqmrE5aIzH&t=404)

It seems very likely that this is already fixed by the above commit.
