### ISSUE TITLE
Red Alarm - samples missing

### ISSUE THREAD

**Issue by Sebbo401** [skyfloogle/red-viper#36] opened 2024-03-04 10:24 UTC
Hi - awesome emulator. Thank you so much. Have some problems playing red alarm:

- the voice samples are missing

- not possible to finish first stage, freeze, but not reproducible as always on different parts

Using New 3DS XL

**Comment by vaguerant** [comment] 2024-03-04 10:46
Did you update to version 0.9.1? That should have resolved the crashing in Red Alarm, per issues #1 and #6.

**Comment by riggles1** [comment] 2024-03-04 12:07
Nester's Funky Bowling also has missing SFX like the sound of when the bowling ball strikes the pins.
Maybe it's best to rename this issue to only missing samples? If the crashes are gone.

I'm interested in knowing what other samples aren't played back in other games as well.

**Comment by yllekz** [comment] 2024-03-04 13:27
The samples are also missing from Galactic Pinball's title screen FWIW.

**Comment by vaguerant** [comment] 2024-03-04 13:33
> Nester's Funky Bowling also has missing SFX like the sound of when the bowling ball strikes the pins. Maybe it's best to rename this issue to only missing samples? If the crashes are gone.
> 
> I'm interested in knowing what other samples aren't played back in other games as well.

As far as I know, all of them. That's what issue #28 is for.

**Comment by skyfloogle** [comment] 2024-03-04 17:13
Yep, duplicate of #28.

**Closed** 2024-03-04 17:13 UTC
